export type Colorsprops = {
  normal: string;
  fighting: string,
  flying: string,
  poison: string,
  ground: string,
  rock: string,
  bug: string,
  ghost: string,
  steel: string,
  fire: string,
  water: string,
  grass: string,
  electric: string,
  psychic: string,
  ice: string,
  dragon: string,
  dark: string,
  fairy: string,
}

export const ColorsType: Colorsprops = {
  normal: '#BCBDAE',
  fighting: '#A55645',
  flying: '#7AA4FF',
  poison: '#CF8BFF',
  ground: '#F0CA56',
  rock: '#CEBC72',
  bug: '#C0D21C',
  ghost: '#7875D6',
  steel: '#C3C1D7',
  fire: '#F85542',
  water: '#55AEFE',
  grass: '#A0D98C',
  electric: '#FCE53F',
  psychic: '#F763B4',
  ice: '#94F1FE',
  dragon: '#8B76FF',
  dark: '#8D6956',
  fairy: '#FAACFF',
};
